# Ruff configuration for CI system project
# https://docs.astral.sh/ruff/configuration/

[lint]
# Enable specific rule categories
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes (includes unused imports)
    "I",   # isort (import sorting)
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
]

# Ignore specific rules
ignore = [
    "E501",  # Line too long (let formatter handle it)
    "B904",  # Use 'raise ... from err' (sometimes not needed)
]

# Exclude test fixtures (they are intentionally broken)
exclude = [
    "tests/fixtures",
]

[lint.per-file-ignores]
# Allow unused imports in __init__.py files
"__init__.py" = ["F401"]
# FastAPI routes use File() in defaults - this is idiomatic
"ci_server/app.py" = ["B008"]
